### ISSUE TITLE
trycourier => courier

### ISSUE THREAD

**Issue by Riccardo1976** [GauriSP10/streamlit_login_auth_ui#28]
Using Python3.11 on RH

Trying to use `__login__` throws an error:

```
2024-05-04 08:12:24.438 Uncaught app exception
Traceback (most recent call last):
  File "/home/riccardo/Repos/streamlit/venv/lib64/python3.11/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 584, in _run_script
    exec(code, module.__dict__)
  File "/home/riccardo/Repos/streamlit/app.py", line 6, in <module>
    from streamlit_login_auth_ui.widgets import __login__
  File "/home/riccardo/Repos/streamlit/venv/lib64/python3.11/site-packages/streamlit_login_auth_ui/__init__.py", line 1, in <module>
    from streamlit_login_auth_ui.widgets import __login__
  File "/home/riccardo/Repos/streamlit/venv/lib64/python3.11/site-packages/streamlit_login_auth_ui/widgets.py", line 7, in <module>
    from .utils import check_usr_pass
  File "/home/riccardo/Repos/streamlit/venv/lib64/python3.11/site-packages/streamlit_login_auth_ui/utils.py", line 3, in <module>
    from trycourier import Courier
ModuleNotFoundError: No module named 'trycourier'
```

Installing `trycourier` itself does not solve the issue,

Changing:
```
streamlit_login_auth_ui/utils.py", line 3
```

`from trycourier import Courier` => `import courier` seems to resolve the issue.

Considering that this repo is over two years old and that the README tells us to install _specific_ versions of `requirements.txt` i'm hoping you can find the time to do a rehash of the sourcecode to 2024. I'd try it too, but im not proficient enough.

**Comment by kalakala-maker** [comment]
Replace the line `from trycourier import Courier` with `from courier.client import Courier`.

Then, execute the command `pip install argon2-cffi` in your terminal to support the use of `from argon2 import PasswordHasher`.

After these adjustments, your application should run without any issues.

**Comment by ghost** [comment]
> Replace the line `from trycourier import Courier` with `from courier.client import Courier`.
> 
> Then, execute the command `pip install argon2-cffi` in your terminal to support the use of `from argon2 import PasswordHasher`.
> 
> After these adjustments, your application should run without any issues.

thanks a lot this fixed everything

**Comment by tingruizhang** [comment]
I also encountered this problem. When the problem will be fixed?

**Comment by Rycen7822** [comment]
> I also encountered this problem. When the problem will be fixed?

You can try the version I forked
https://github.com/Rycen7822/streamlit_login_auth_ui_zh
